[package]
name = "emigrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.25"
humantime = "2.1.0"
lazy_static = "1.4.0"
regex = "1.8.3"
termcolor = "1.2.0"
